### ISSUE TITLE
Device non activate for some sensors

### ISSUE THREAD

**Issue by GusMuche** [GusMuche/homebridge-zipabox-platform#15]
Issue from Thierry

Device is working with correct value but symbol in Home App stay as unactive

**Comment by GusMuche** [comment]
@thierry13790

J'ai l'impression que c'est normal en fait.

Voir exemple ici https://9to5mac.com/2018/08/22/homekit-weekly-hyperlocal-temperature-and-humidity-with-siri-and-the-home-app/

**Comment by GusMuche** [comment]
Autre piste : voir pour le statut actif, je ne sais pas encore ce qu’il fait réellement.

La nouvelle doc de homebridge peut vraiment aider : https://developers.homebridge.io/#/characteristic/StatusActive

**Comment by thierry13790** [comment]
Oui je pense que c’est faisable avec le status si je me souviens bien j’avais touché à ça lors de la première intégration de ton code avec l’api il y a 6 mois je peux voir si tu veux et essayer de te proposer une solution !
Sinon pour le reste j’ai basculé sur ta release stable et pour l’instant tout est ok merci ! 

Cordialement 

Thierry

Devise ''on a toujours du temps pour faire ce que l'on a envie de faire...''

**Comment by GusMuche** [comment]
Je vais voir pour tester cela encore cette semaine, c’est assez facile à implémenter et tester. Avant j’essaye de finir la prochaine release stable qui est en cours de test grandeur nature chez moi

**Comment by thierry13790** [comment]
Merci super ! 

La release que j’ai installé il y a 2 jours est ok 👌mis à part ça merci 

Thierry

Devise ''on a toujours du temps pour faire ce que l'on a envie de faire...''

**Comment by GusMuche** [comment]
J'ai testé avec le statut actif. Home App reconnait bien l'info mais l'icône reste grise.
As-tu déjà vu un accessoires type temperature avec la couleur pleine?

**Comment by thierry13790** [comment]
Oui effectivement je viens de chercher un capteur de température compatible nativement avec HomeKit et tu as raison ce n’est pas en couleur pleine 

Exemple avec ce capteur de Température :

https://www.google.fr/amp/s/www.igen.fr/tests/2017/07/test-de-leve-degree-un-capteur-de-temperature-compatible-homekit-100557%3famp

Donc rien à faire de ce côté là alors ! 

Merci ! 

Thierry

Devise ''on a toujours du temps pour faire ce que l'on a envie de faire...''
