### ISSUE TITLE
Invalid jsonresponse

### ISSUE THREAD

**Issue by thierry13790** [GusMuche/homebridge-zipabox-platform#25]
Bonjour 
J’ai cette erreur dans les logs même avec la dernière version 
Merci d’avance 
Thierry 

![263152AD-CAD4-4D86-B9F9-FF70DEB0C3DF](https://user-images.githubusercontent.com/21205587/82359857-c42e3580-9a08-11ea-8ad7-edcaf4c698c5.jpeg)

**Comment by GusMuche** [comment]
Besoin de plus d’info :

- remote ou local ?
- Autre erreur avec d’autres accessoires ?
- peux-tu svp copier le config de cet accessoire Temp Jardin ?

A ce stade je vois une erreur dans le retour de la box, une alternative est de voir si la requête en manuel passe

**Comment by thierry13790** [comment]
C'est en remote,  pas d'autres erreurs avec d'autres accessoires, et du coup je pense avoir trouvé
le pb en comparant avec d'autres capteurs de T°, l'erreur est lié au parametrage de status 

Ma config : 

![image](https://user-images.githubusercontent.com/21205587/82446843-abc12800-9aa7-11ea-8fc8-11cfc8401e76.png)

Si je passe noStatus=false 

![image](https://user-images.githubusercontent.com/21205587/82446762-8c29ff80-9aa7-11ea-83da-82a34dc291cc.png)

J'ai d'autres capteurs de T° avec pas d'erreur mais ceux cis sont des capteurs de temperature virtuels alors que celui est directement connecté sur la zipabox c'est un Oregon scientific et il a plusieurs valeurs possibles : humidité ou Temperature ceci explique peut etre le probleme. A noter egalement que ce capteur fonctionne malgré l'erreur dont on parle via homebridge la bonne Temperature s'affiche.

**Comment by GusMuche** [comment]
Vérifie bien le UUID fourni. Il doit être celui de l’attribut Temperature du plus bas niveau. 

Possible de tester via une requête API depuis l’interface de Zipato en communiquant la valeur dans la requête attributes/{UUID}/statuses (de mémoire)

**Comment by thierry13790** [comment]
Ok je vais contrôler ça merci de l’info

**Comment by GusMuche** [comment]
Il existe aussi une requête API qui liste tous les status dispo. Je pense coder cela afin que le plugin prévienne si le UUID fourni n’est pas dans la liste. Ca évitera l’apparition d’erreurs liées à cela.

**Comment by thierry13790** [comment]
Bonne idée

**Comment by GusMuche** [comment]
Peux-tu svp tester avec la nouvelle version et me dire si le problème est toujours présent ?

**Comment by thierry13790** [comment]
Merci oui je reste vite 

Thierry

Devise ''on a toujours du temps pour faire ce que l'on a envie de faire...''

**Comment by thierry13790** [comment]
C'est installé je te tiens au courant le problème n'apparaissait pas de suite j'attend quelques jours et te donne le status !

**Comment by GusMuche** [comment]
Des nouvelles de cette erreur ?

**Comment by thierry13790** [comment]
Bonjour 

Le problème est résolu merci Gusmuche ! 

Thierry
