### ISSUE TITLE
Désactivation du status de la batterie possible ? 

### ISSUE THREAD

**Issue by thierry13790** [GusMuche/homebridge-zipabox-platform#28]
J’ai 2 capteurs qui affichent la température mais sans avoir une batterie, pourtant sur HomeKit il est affiché que la batterie est basse pour ces 2 accessoires, comment désactiver la batterie sur l’affichage ?

**Comment by GusMuche** [comment]
As-tu essayé avec "batteryLimit" = 0 ?

Si cela marche je pourrai corriger efficacement, sinon je dois chercher

**Comment by thierry13790** [comment]
Oui avec batterie limit 0 même problème 
Également si j’active noStatus = True

**Comment by GusMuche** [comment]
Bizarre, normalement le plugin vérifie via l'API si l'accessoire est sur secteur ou non.
Peux-tu éventuellement me donner le retour de la requête API devices/' + uuidDevice + '/status via l'interface API de my.zipato.com?
Avec ca je peux voir le genre de retour que ces accessoires donnent car je n'ai pas le cas chez moi.

**Comment by GusMuche** [comment]
(Attention qu'il faut le uuid du device et pas de l'attribut)

**Comment by GusMuche** [comment]
Alternative : via l'application Eve ou à l'ajout au début sur HomeKit : essayer de lancer la méthode identify et me donner le retour dans le log

**Comment by GusMuche** [comment]
Autre alternative : tu peux tester avec le package homebridge-zipabox-platform-dev en version 1.6.39. 
J'ai désactivé le lien vers le status batterie faible si la limite fixée est nulle et remis par défaut à zéro. Donc si tu ne spécifie rien sur batteryLimit le plugin devrait ne pas ajouter l'option batterie faible

La version 1.6.39 a aussi la nouvelle validation de l'UUID au démarrage.

Pour tester cette version il faut d'abord désinstaller l'autre package, sinon il y aura conflit entre les plugin

**Comment by thierry13790** [comment]
Merci pour ton aide, en fait il n'y a pas d'attribut state pour un virtual accessoire 

Exemple : 

![image](https://user-images.githubusercontent.com/21205587/82731951-6badaf80-9d0a-11ea-956c-151e0cfa131f.png)

Ceci explique le probleme.

Pour reproduire je te suggere de créer un virtuel temperature sensor et voir le probleme

**Comment by thierry13790** [comment]
> Bizarre, normalement le plugin vérifie via l'API si l'accessoire est sur secteur ou non.
> Peux-tu éventuellement me donner le retour de la requête API devices/' + uuidDevice + '/status via l'interface API de my.zipato.com?
> Avec ca je peux voir le genre de retour que ces accessoires donnent car je n'ai pas le cas chez moi.

[
  {
    "uuid": "3689d239-132b-466c-b09a-22d7a98eb970",
    "state": {
      "raw": {
        "device": "3689d239-132b-466c-b09a-22d7a98eb970",
        "trouble": false,
        "receiveTimestamp": 1590214975624,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "OFFLINE",
        "started": true,
        "mainsPower": false,
        "online": false
      },
      "online": false,
      "trouble": false,
      "started": false,
      "receiveTimestamp": "2020-05-23T06:22:55Z",
      "onlineState": "OFFLINE",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "8af99bbd-39f7-4097-bac1-6fc9ad9a9201",
    "state": {
      "sentTimestamp": "2020-05-23T06:28:09Z",
      "raw": {
        "device": "8af99bbd-39f7-4097-bac1-6fc9ad9a9201",
        "trouble": false,
        "receiveTimestamp": 1590214991190,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 1590215289805,
        "onlineState": "OFFLINE",
        "mainsPower": true,
        "online": false
      },
      "online": false,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T06:23:11Z",
      "onlineState": "OFFLINE",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": true
    }
  },
  {
    "uuid": "2be2db68-7d0b-47eb-a627-05fdeb22228f",
    "state": {
      "batteryTimestamp": "2019-12-12T22:03:58Z",
      "sentTimestamp": "2020-05-23T06:26:18Z",
      "raw": {
        "device": "2be2db68-7d0b-47eb-a627-05fdeb22228f",
        "trouble": false,
        "receiveTimestamp": 1590214990499,
        "batteryTimestamp": 1576188238499,
        "batteryLevel": 4,
        "sentTimestamp": 1590215178325,
        "onlineState": "OFFLINE",
        "mainsPower": true,
        "online": false
      },
      "online": false,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T06:23:10Z",
      "onlineState": "OFFLINE",
      "timestamp": null,
      "batteryLevel": 4,
      "mainsPower": true
    }
  },
  {
    "uuid": "a38c999b-2afe-481e-a5af-c1e972dbe355",
    "state": {
      "raw": {
        "device": "a38c999b-2afe-481e-a5af-c1e972dbe355",
        "trouble": false,
        "receiveTimestamp": 1589917662747,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:42Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "498916e9-4a80-4d62-9366-13408a8a5bf1",
    "state": {
      "raw": {
        "device": "498916e9-4a80-4d62-9366-13408a8a5bf1",
        "trouble": false,
        "receiveTimestamp": 1589917670344,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:50Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "46ff25fc-40d0-45f2-afdb-e450b7ddf319",
    "state": {
      "batteryTimestamp": "2020-02-26T23:50:54Z",
      "raw": {
        "device": "46ff25fc-40d0-45f2-afdb-e450b7ddf319",
        "trouble": false,
        "receiveTimestamp": 1590214991435,
        "batteryTimestamp": 1582761054081,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "OFFLINE",
        "mainsPower": false,
        "online": false
      },
      "online": false,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T06:23:11Z",
      "onlineState": "OFFLINE",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "ecba4d02-813c-479f-b90f-68a692181208",
    "state": {
      "raw": {
        "device": "ecba4d02-813c-479f-b90f-68a692181208",
        "trouble": false,
        "receiveTimestamp": 1589917670593,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:50Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "732d02fe-684c-49c6-a7ac-1fa22e443568",
    "state": {
      "batteryTimestamp": "2020-05-23T12:29:02Z",
      "sentTimestamp": "2020-05-23T13:05:53Z",
      "raw": {
        "device": "732d02fe-684c-49c6-a7ac-1fa22e443568",
        "trouble": false,
        "receiveTimestamp": 1590237303558,
        "batteryTimestamp": 1590236942487,
        "batteryLevel": 100,
        "sentTimestamp": 1590239153385,
        "onlineState": "ONLINE",
        "mainsPower": true,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T13:05:53Z",
      "onlineState": "ONLINE",
      "timestamp": null,
      "batteryLevel": 100,
      "mainsPower": true
    }
  },
  {
    "uuid": "74afbf65-6b6c-48a6-b396-66986cf56442",
    "state": {
      "batteryTimestamp": "2020-05-23T13:26:43Z",
      "raw": {
        "device": "74afbf65-6b6c-48a6-b396-66986cf56442",
        "trouble": false,
        "receiveTimestamp": 1590240349959,
        "batteryTimestamp": 1590240349959,
        "batteryLevel": 90,
        "sentTimestamp": 0,
        "onlineState": "ONLINE",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T13:26:43Z",
      "onlineState": "ONLINE",
      "timestamp": null,
      "batteryLevel": 90,
      "mainsPower": false
    }
  },
  {
    "uuid": "4d57a906-887d-41f8-82e4-177da07425b1",
    "state": {
      "sentTimestamp": "2020-05-23T13:29:23Z",
      "raw": {
        "device": "4d57a906-887d-41f8-82e4-177da07425b1",
        "trouble": false,
        "receiveTimestamp": 1590240464415,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 1590240562928,
        "onlineState": "ONLINE",
        "mainsPower": true,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T13:29:23Z",
      "onlineState": "ONLINE",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": true
    }
  },
  {
    "uuid": "02e7a845-59ff-4918-8b89-71bd9cbd7bcc",
    "state": {
      "batteryTimestamp": "2020-05-23T13:27:58Z",
      "raw": {
        "device": "02e7a845-59ff-4918-8b89-71bd9cbd7bcc",
        "trouble": false,
        "receiveTimestamp": 1590240439106,
        "batteryTimestamp": 1590240439106,
        "batteryLevel": 90,
        "sentTimestamp": 0,
        "onlineState": "ONLINE",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T13:27:58Z",
      "onlineState": "ONLINE",
      "timestamp": null,
      "batteryLevel": 90,
      "mainsPower": false
    }
  },
  {
    "uuid": "63e68bab-91ed-44ca-af27-11f680813888",
    "state": {
      "batteryTimestamp": "2020-05-23T13:25:05Z",
      "raw": {
        "device": "63e68bab-91ed-44ca-af27-11f680813888",
        "trouble": false,
        "receiveTimestamp": 1590240262263,
        "batteryTimestamp": 1590240262263,
        "batteryLevel": 90,
        "sentTimestamp": 0,
        "onlineState": "ONLINE",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-23T13:25:05Z",
      "onlineState": "ONLINE",
      "timestamp": null,
      "batteryLevel": 90,
      "mainsPower": false
    }
  },
  {
    "uuid": "8b4022f0-e8d7-44eb-bf61-cbf6d3d299f7",
    "state": {
      "raw": {
        "device": "8b4022f0-e8d7-44eb-bf61-cbf6d3d299f7",
        "trouble": false,
        "receiveTimestamp": 1589917670696,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:50Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "a99c6b50-d90b-4826-8eb4-ab555bba0b88",
    "state": {
      "raw": {
        "device": "a99c6b50-d90b-4826-8eb4-ab555bba0b88",
        "trouble": false,
        "receiveTimestamp": 1589917659245,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:39Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "d5109b4e-0e5d-4e7c-a713-83e0bfa932ec",
    "state": {
      "raw": {
        "device": "d5109b4e-0e5d-4e7c-a713-83e0bfa932ec",
        "trouble": false,
        "receiveTimestamp": 1589917658613,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:38Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "a3193606-9179-4436-8f58-989a9d5bd7c7",
    "state": {
      "raw": {
        "device": "a3193606-9179-4436-8f58-989a9d5bd7c7",
        "trouble": false,
        "receiveTimestamp": 1589917670470,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:50Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  },
  {
    "uuid": "4c374b87-dbbf-426c-8617-aa194b4fe5a5",
    "state": {
      "raw": {
        "device": "4c374b87-dbbf-426c-8617-aa194b4fe5a5",
        "trouble": false,
        "receiveTimestamp": 1589917668563,
        "batteryTimestamp": 0,
        "batteryLevel": 0,
        "sentTimestamp": 0,
        "onlineState": "INTERNAL",
        "mainsPower": false,
        "online": true
      },
      "online": true,
      "trouble": false,
      "receiveTimestamp": "2020-05-19T19:47:48Z",
      "onlineState": "INTERNAL",
      "timestamp": null,
      "batteryLevel": 0,
      "mainsPower": false
    }
  }
]
Response Code
200
Response Headers

**Comment by thierry13790** [comment]
> Alternative : via l'application Eve ou à l'ajout au début sur HomeKit : essayer de lancer la méthode identify et me donner le retour dans le log

Cette appli ? 

https://github.com/pyeve/eve

**Comment by GusMuche** [comment]
> Merci pour ton aide, en fait il n'y a pas d'attribut state pour un virtual accessoire
> 
> Exemple :
> 
> ![image](https://user-images.githubusercontent.com/21205587/82731951-6badaf80-9d0a-11ea-956c-151e0cfa131f.png)
> 
> Ceci explique le probleme.
> 
> Pour reproduire je te suggere de créer un virtuel temperature sensor et voir le probleme

En fait je parle parfois de `STATE` mais n'importe quel UUID de bas niveau fait l'affaire. Dans ton exemple tu peux utiliser le UUID du dernier niveau qui est nommé `TEMPERATURE` et ça devrait marcher.

Ensuite si cela ne marche pas va dans l'API de zipato et tu entre le UUID dans la requête. Avec ce retour là je comprendrai (dans le précédent je n'ai pas su retrouver la référence de la température.
<img width="1005" alt="Capture d’écran 2020-05-23 à 21 34 19" src="https://user-images.githubusercontent.com/45716856/82739129-5605ad80-9d3d-11ea-829a-ff891831f86f.png">

**Comment by GusMuche** [comment]
> > Alternative : via l'application Eve ou à l'ajout au début sur HomeKit : essayer de lancer la méthode identify et me donner le retour dans le log
> 
> Cette appli ?
> 
> https://github.com/pyeve/eve

Non, via iOS tu peux installer l'APP de EVE (elle s'appelle EVE...) et l'appli utilise les devices HomeKit et affiche parfois plus d'info. Tu peux aussi y activer l'option "Identité" qui n'est disponible qu'à l'ajout dans l'appli Home de iOS. C'est là aussi que le plugin permet d'afficher le niveau réel de la batterie et pas seulement si la batterie est faible
