### ISSUE TITLE
Homebridge Zipabox Platform stop working after few hours

### ISSUE THREAD

**Issue by Mikis83** [GusMuche/homebridge-zipabox-platform#32]
Hi, I would like to get assistance,
Homebridge Zipabox Platform stop working after few hours, and there is no connection to the homekit,
I need to restart the homebridge to reconnect to zipato again.

Attached log file:

[Homebridge Zipabox Platform - error.txt](https://github.com/GusMuche/homebridge-zipabox-platform/files/5577365/Homebridge.Zipabox.Platform.-.error.txt)

Thanks!

**Comment by GusMuche** [comment]
Hi Mikis83,

Seems that you config for local access. The plugin didn't find your zipato box in your network. Are you sure that all router, server, homebridge and zipato box are online each time ?

Also I've validate local network for my box working in v2. When you connect to dashboard, are you in v2 or v3? (website my.zipato.com or my3.zipato.com)

If you're on v3 you need to wait to next version. If in v2, maybe working with remote access will solve you issue.

I've encounter same issue a few times but I never success to reproduce it. I work on synology was and need a restart to get all on line.

**Comment by GusMuche** [comment]
Hi Mikis83,

Have you try something with this issue ? 

I just update the dev branch and dev package and use it on the v3 without problem of disconnection. 

Also for V3 it's not possible to use local access to the API of the box. Maybe Zipato will change this in the future...

**Comment by GusMuche** [comment]
Final solution to test : force the use of other DNS for your docker installation (if you use docker). I have same problem recently and that solve the problem.

Ticket close for delay.
