### ISSUE TITLE
No dimmer in accessories type list

### ISSUE THREAD

**Issue by dinonovak** [GusMuche/homebridge-zipabox-platform#35]
I am using homebridge-zipabox-platform v1.8.0
in the accessories type list I do not see dimmer as Type of accessory,
anything special needed to enable it?

**Comment by GusMuche** [comment]
Hello,

I think you talk about the list found inside the plugin parameters from the config-ui interface.
I check and yes, I forgot to add this type inside the drop down list.
But you can still configure it directly in your config.json.

Follow this process : 
1. Configure through the config-ui plugin parameters like a simple light
2. Save - No reboot needed
3. Go to the tab "Config" in config-ui 
4. Found your light and change the parameter from "type": "light" to "type" : "dimmer" 
5. Save and reboot

Let me know if this work or not.

**Comment by GusMuche** [comment]
Alternativ : you can update to 1.8.1

**Comment by dinonovak** [comment]
Thanx, already fixed it yesterday in json manually. so it works
